GET http://localhost:8000

###
GET http://localhost:8000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlenJhNDk5OEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoyMCwiZXhwIjoxNzIwODAzODcwfQ.UpFpw1Pji_bzuoXaflQb5q0CK4CTYHIP8J8VVyRhNDs

###
GET http://localhost:8000/users?limit=1
Authorization: 

###
GET http://localhost:8000/users/20
Authorization: 
###
GET http://localhost:8000/user-booking/20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlenJhNDk5OEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MjA3OTgwMzR9.qAb7ftQAEWP-c5fJp34jxhQyYcPhmi3Qavjp72mJo0k

###
GET http://localhost:8000/users-support/22
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlenJhNDk5OEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MjA3OTgwMzR9.qAb7ftQAEWP-c5fJp34jxhQyYcPhmi3Qavjp72mJo0k


###
PUT http://localhost:8000/users/21
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbGlzaGFraXBsYW5nYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInVzZXJfaWQiOjIxLCJleHAiOjE3MjA4ODU3MTR9.f8DKn5c9q2_T79ZIRNB-aIxNDbUVqGbPWMXzuKnOY4k
Content-Type: application/json

{
    "full_name": "Elisha K"
}

###
DELETE http://localhost:8000/delete/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###---------------------------------------Register (user, auth tables)--
POST http://localhost:8000/register
Content-Type: application/json

{
    "full_name": "Ezra",
    "email": "ezra4998@gmail.com",
    "contact_phone": "1234567890",
    "address": "123 Main St",
    "role": "admin",
    "password": "password"
}

###--------------------------------------Login (user, auth tables)-----------
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "ezra4998@gmail.com",
    "password": "password"

}

###     ---------------------------------

###
GET http://localhost:8000/vehicles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlenJhNDk5OEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MjA3OTgwMzR9.qAb7ftQAEWP-c5fJp34jxhQyYcPhmi3Qavjp72mJo0k


###--- vehicle details
GET http://localhost:8000/vehicleDetails
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlenJhNDk5OEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoyMCwiZXhwIjoxNzIwOTA1MDIzfQ.qasawLnzwcyorRqwUIIXkAtp6lJI2VL_ifke93adUqM

###
GET http://localhost:8000/vehicles?limit=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlenJhNDk5OEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoyMCwiZXhwIjoxNzIwODk4Mzg4fQ.GZG68NHnfWXOCPwdO3irnsADjv5o7UdEMC2O7FEK6qA

###
GET http://localhost:8000/vehicles/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
POST http://localhost:8000/vehicles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
    "vehicle_specs_id": 1,
    "rental_rate": 2,
    "availability": true,
    "created_at": "2024-07-07 14:52:20.163",
    "updated_at": "2024-07-07 14:52:20.163"
}

###
PUT http://localhost:8000/vehicles/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
    "availability": false
}

###
DELETE http://localhost:8000/vehicles/delete/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og


###     ---------------------------------

###
GET http://localhost:8000/vehicleSpecifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/vehicleSpecifications?limit=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/vehicleSpecifications/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
POST http://localhost:8000/vehicleSpecifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
    "manufacturer": "Tesla",
    "model": "Cybertruck",
    "year": 2023,
    "fuel_type": "null",
    "engine_capacity": "1000cc",
    "transmission": "1000hp",
    "seating_capacity": 4,
    "color": "black",
    "features": "beast"
}

###
PUT http://localhost:8000/vehicleSpecifications/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
   "features": "normal"
}

###
DELETE http://localhost:8000/vehicleSpecifications/delete/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og


###     ---------------------------------

###
GET http://localhost:8000/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDEwODYzOH0.WD7SDzaQ8FNACyfNP9HsXJOspCiquhEDzEJi8O4hVng

###
GET http://localhost:8000/bookings?limit=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/bookings/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
POST http://localhost:8000/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDEwODYzOH0.WD7SDzaQ8FNACyfNP9HsXJOspCiquhEDzEJi8O4hVng
Content-Type: application/json

{
    "user_id": 1,
    "vehicle_id": 1,
    "location_id": 1,
    "booking_date": "2024-07-04 14:52:20.163",
    "return_date": "2024-07-07 14:52:20.163",
    "total_amount": 12000,
    "booking_status": "pending",
    "created_at": "2024-07-07 14:52:20.163",
    "updated_at": "2024-07-07 14:52:20.163"
}

###
PUT http://localhost:8000/bookings/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
   "booking_status": "complete"
}

###
DELETE http://localhost:8000/bookings/delete/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###     ---------------------------------

###
GET http://localhost:8000/payments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/payments?limit=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/payments/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
POST http://localhost:8000/payments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
    "payment_id": 1,
    "booking_id": 2,
    "amount": 2,
    "payment_status": "pending",
    "payment_date": "2024-07-04",
    "transaction_id": "SJKHJ4HS44",
    "created_at": "2024-07-07 14:52:20.163",
    "updated_at": "2024-07-07 14:52:20.163"
}

###
PUT http://localhost:8000/payments/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
   "payment_status": "complete"
}

###
DELETE http://localhost:8000/payments/delete/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###     ---------------------------------

###
GET http://localhost:8000/supportTickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/supportTickets?limit=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/supportTickets/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
POST http://localhost:8000/supportTickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
    "user_id": 1,
    "subject": "login problem",
    "description": "login problem",
    "status": "pending",
    "created_at": "2024-07-07 14:52:20.163",
    "updated_at": "2024-07-07 14:52:20.163"
}

###
PUT http://localhost:8000/supportTickets/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
   "status": "complete"
}

###
DELETE http://localhost:8000/supportTickets/delete/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###     ---------------------------------

###
GET http://localhost:8000/locations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDM3NDYwNX0.eCsMTRe65HKlbunBa-N2AGFx2asxjZxVlXTt4ZWsWg0
###
GET http://localhost:8000/locations?limit=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/locations/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###
GET http://localhost:8000/locations-branches/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlenJhNDk5OEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MjA3OTgwMzR9.qAb7ftQAEWP-c5fJp34jxhQyYcPhmi3Qavjp72mJo0k

###
POST http://localhost:8000/locations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDM3NDYwNX0.eCsMTRe65HKlbunBa-N2AGFx2asxjZxVlXTt4ZWsWg0
Content-Type: application/json

{
    "name": "London",
    "address": "123 leicester square",
    "created_at": "2024-07-07 14:52:20.163",
    "updated_at": "2024-07-07 14:52:20.163"
}

###
PUT http://localhost:8000/locations/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og
Content-Type: application/json

{
   "address": "123 north London"
}

###
DELETE http://localhost:8000/locations/delete/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA5MzQ5Mn0.bfh9sCV4wXdwPd8P1TjJH7-QecpEIdSTPD-SMokQ3Og

###     ---------------------------------

###
GET http://localhost:8000/branches

###
GET http://localhost:8000/branches?limit=1

###
GET http://localhost:8000/branches/1

###
POST http://localhost:8000/branches
Content-Type: application/json

{
    "name": "Street 24",
    "location_id": 1,
    "contact_phone": "+1231231232",
    "created_at": "2024-07-07 14:52:20.163",
    "updated_at": "2024-07-07 14:52:20.163"
}

###
PUT http://localhost:8000/branches/1
Content-Type: application/json

{
   "contact_phone": "+1231231231"
}

###
DELETE http://localhost:8000/branches/delete/1

###     ---------------------------------

###
GET http://localhost:8000/fleets

###
GET http://localhost:8000/fleets?limit=1

###
GET http://localhost:8000/fleets/1

###
POST http://localhost:8000/fleets
Content-Type: application/json

{
    "vehicle_id": 1,
    "acquisition_date": "2024-07-04 14:52:20.163",
    "depreciation_rate": 2.3,
    "current_value": 2499999,
    "maintenance_cost": 11299,
    "status": "done",
    "created_at": "2024-07-07 14:52:20.163",
    "updated_at": "2024-07-07 14:52:20.163"
}

###
PUT http://localhost:8000/fleets/1
Content-Type: application/json

{
   "maintenance_cost": 20000
}

###
DELETE http://localhost:8000/fleets/delete/1

###
POST http://localhost:8000/create-payment-intent
Content-Type: application/json

{
  "amount": 1000,
  "currency": "usd"
}
