GET http://localhost:8000

###
GET http://localhost:8000/users

###
GET http://localhost:8000/users?limit=1

###
GET http://localhost:8000/users/1

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "full_name": "John Doe",
    "email": "johndoe@gmail.com",
    "contact_phone": "+1234567890",
    "address": "123 Main St, New York, NY 10001",
    "role": "admin",
    "created_at": "2024-07-02",
    "updated_at": "2024-07-02"
}

###
PUT http://localhost:8000/users/3
Content-Type: application/json

{
    "full_name": "John Doe 2"
}

###
DELETE http://localhost:8000/delete/4

###---------------------------------------Register (user, auth tables)--
POST http://localhost:8000/register
Content-Type: application/json

{
    "full_name": "John Doe",
    "email": "johndoe1@example.com",
    "contact_phone": "1234567890",
    "address": "123 Main St",
    "role": "user",
    "created_at": "2024-07-02",
    "updated_at": "2024-07-02",
    "password": "password"
}